const properties = [
    {
        id: 1,
        title: "Emerald Estate",
        location: "Lugbe, Abuja",
        badge: "LUGBE",
        price: "₦95,000,000",
        beds: 4,
        baths: 5,
        cars: 3,
        type: "Detached Duplex",
        estate: "Emerald",
        image: "images/BUCKCREST HAVENS EMERALD ESTATE/4 BEDROOM DETACHED DUPLEX  (1).jpg"
    },
    {
        id: 2,
        title: "Peridot Estate",
        location: "Kuje, Abuja",
        badge: "KUJE",
        price: "₦35,000,000",
        beds: 3,
        baths: 4,
        cars: 2,
        type: "Apartment",
        estate: "Peridot",
        image: "images/BUCKCREST HAVENS PERIDOT ESTATE/IMG-20241007-WA0007.jpg"
    },
    {
        id: 3,
        title: "Dawaki Heights",
        location: "Dawaki, Abuja",
        badge: "DAWAKI",
        price: "₦120,000,000",
        beds: 4,
        baths: 5,
        cars: 4,
        type: "Detached Duplex",
        estate: "Dawaki",
        image: "images/dAWAKI/4 BED FULLY.jpg"
    },
    {
        id: 4,
        title: "Kabusa Court",
        location: "Kabusa, Abuja",
        badge: "KABUSA",
        price: "₦55,000,000",
        beds: 4,
        baths: 4,
        type: "Terrace Duplex",
        estate: "Kabusa",
        image: "images/KABUSA PROTOTYPE/TERRACE 1.jpg"
    },
    {
        id: 5,
        title: "Emerald Terrace",
        location: "Lugbe, Abuja",
        badge: "LUGBE",
        price: "₦65,000,000",
        beds: 3,
        baths: 4,
        cars: 2,
        type: "Terrace Duplex",
        estate: "Emerald",
        image: "images/BUCKCREST HAVENS EMERALD ESTATE/3 BEDROOM TERRACE DUPLEX  (1).jpg"
    },
    {
        id: 6,
        title: "Kuje IV Residences",
        location: "Kuje, Abuja",
        badge: "KUJE IV",
        price: "₦28,000,000",
        beds: 3,
        baths: 3,
        type: "Semi-Detached",
        estate: "Kuje",
        image: "images/hero_mansion.png"
    },
    {
        id: 7,
        title: "Jordan Valley (4 Bed)",
        location: "Lugbe, Abuja (Behind NTA Quarters)",
        badge: "FCDA APPROVED",
        price: "₦8,500,000",
        beds: 4,
        baths: 4,
        cars: 3,
        type: "Fully Detached Duplex",
        estate: "Jordan Valley",
        image: "images/jordan_valley.png"
    },
    {
        id: 8,
        title: "Jordan Valley (5 Bed)",
        location: "Lugbe, Abuja (Behind NTA Quarters)",
        badge: "FCDA APPROVED",
        price: "₦9,500,000",
        beds: 5,
        baths: 5,
        cars: 3,
        type: "Fully Detached Duplex",
        estate: "Jordan Valley",
        image: "images/jordan_valley.png"
    },
    {
        id: 9,
        title: "HighLand City (2 Bed)",
        location: "Kuje, Abuja (Behind Centenary City)",
        badge: "15% DISCOUNT",
        price: "₦3,400,000",
        beds: 2,
        baths: 2,
        cars: 1,
        type: "Terrace Duplex",
        estate: "HighLand City",
        image: "images/highland_city.png"
    },
    {
        id: 10,
        title: "HighLand City (3 Bed)",
        location: "Kuje, Abuja (Behind Centenary City)",
        badge: "15% DISCOUNT",
        price: "₦4,250,000",
        beds: 3,
        baths: 3,
        cars: 2,
        type: "Terrace Duplex",
        estate: "HighLand City",
        image: "images/highland_city.png"
    },
    {
        id: 11,
        title: "HighLand City (4 Bed)",
        location: "Kuje, Abuja (Behind Centenary City)",
        badge: "15% DISCOUNT",
        price: "₦5,500,000",
        beds: 4,
        baths: 4,
        cars: 3,
        type: "Penthouse Bungalow",
        estate: "HighLand City",
        image: "images/highland_city.png"
    },
    {
        id: 12,
        title: "HighLand City (5 Bed)",
        location: "Kuje, Abuja (Behind Centenary City)",
        badge: "15% DISCOUNT",
        price: "₦6,370,000",
        beds: 5,
        baths: 5,
        cars: 3,
        type: "Fully Detached Duplex",
        estate: "HighLand City",
        image: "images/highland_city.png"
    }
];

window.propertyData = properties;
